[package]
name = "sputnikdao2"
version = "2.0.0"
authors = ["Sputnik Devs <near-daos@protonmail.com>"]
edition = "2018"
publish = false

[env]
RUST_BACKTRACE=1


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = {path="/home/gentbinaku/near/near-sdk-rs/near-sdk"}
near-sys = {path="/home/gentbinaku/near/near-sdk-rs/sys"}
near-contract-standards = {path="/home/gentbinaku/near/near-sdk-rs/near-contract-standards"}
hex = "0.4.2"

[dependencies.serde_with]
version = "1.4.0"

[dev-dependencies]
near-sdk-sim = {path="/home/gentbinaku/near/near-sdk-rs/near-sdk-sim"}
test-token = { path = "../test-token" }
sputnik-staking = { path = "../sputnik-staking" }